### ISSUE TITLE
press enter to continue

### ISSUE THREAD

**Issue by nikinbaidar** [kezhenxu94/vim-mysql-plugin#10]
Great plugin, really like it.
One issue however is that in a tiling window manager running a query with either `leader rr` or `leader rs`  prompts me to `press enter or type a command to continue`, if I have multiple containers open.

Works absolutely perfect when I have only one window open in my tiling window manager. 
PS I am using i3.

Is there a way to solve this?

I think this would go away If i could suppress the "Done! mysql '--default..." message.

**Comment by kezhenxu94** [comment]
> I think this would go away If i could suppress the "Done! mysql '--default..." message.

Hi, having an option to suppress the message is a good idea, would you like to help to file a pull request?

**Comment by nikinbaidar** [comment]
> > I think this would go away If i could suppress the "Done! mysql '--default..." message.
> 
> Hi, having an option to suppress the message is a good idea, would you like to help to file a pull request?

I just had a look at the source code. All that I had to do was comment out line 28 where it says
`echohl Comment | echon 'Done! ...`.  It works just perfectly fine now.

I don't think a pull request is necessary here and I say that with all due respect. Thank you so much for asking though.

**Comment by kezhenxu94** [comment]
OK, I'll close this for now, thanks for reaching out 🙇
